server:
  port: 8000
eureka:
  instance:
    hostname: localhost  #主机名
    prefer-ip-address: true  #当前实例IP注册到EurekaServer,如果是false,就注册主机名↑↑↑↑↑↑↑↑↑↑↑↑
    ip-address: 127.0.0.1  #如果是公网,就写公网ip,当前实例的ip
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}  #eureka 页面显示当前应用的方式
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #访问EurekaServer的路径,Eureka服务地址,客户端使用改地址和Eureka进行通信
spring:
  application:
    name: eureka-provider  #当前应用名称,需要使用该名称获取路径