server:
  port: 8761
#Eureka
eureka:
  instance:
    hostname: eureka-server1  #主机名
  client:
    service-url:
      defaultZone: http://eureka-server2:8762/eureka #集群相互访问
    register-with-eureka: true  #是否将自己的路径注册到Eureka上,Eureka server一般不需要,client(服务提供方)需要注册
    fetch-registry: true  #是否需要从Eureka中抓取路径,Consumer需要
spring:
  application:
    name: eureka-server-ha
